import type { CDNProvider, ConsoleImporterConfig } from '../types';

export const DEFAULT_PROVIDERS: CDNProvider[] = [
  // 全球源
  {
    id: 'jsdelivr',
    name: 'jsDelivr',
    description: 'Fast, reliable, global CDN',
    baseUrl: 'https://cdn.jsdelivr.net',
    enabled: true,
    priority: 1,
    jsTemplate: 'https://cdn.jsdelivr.net/npm/{package}@{version}',
    cssTemplate: 'https://cdn.jsdelivr.net/npm/{package}@{version}',
    searchApi: 'https://api.jsdelivr.com/v1/packages/npm/{package}',
    versionsApi: 'https://api.jsdelivr.com/v1/packages/npm/{package}',
    supportESM: true,
    supportVersions: true,
    region: 'global',
  },
  {
    id: 'unpkg',
    name: 'unpkg',
    description: 'The CDN for JavaScript modules',
    baseUrl: 'https://unpkg.com',
    enabled: true,
    priority: 2,
    jsTemplate: 'https://unpkg.com/{package}@{version}',
    cssTemplate: 'https://unpkg.com/{package}@{version}',
    supportESM: true,
    supportVersions: true,
    region: 'global',
  },
  {
    id: 'esm',
    name: 'esm.sh',
    description: 'A modern ESM CDN',
    baseUrl: 'https://esm.sh',
    enabled: true,
    priority: 3,
    jsTemplate: 'https://esm.sh/{package}@{version}',
    cssTemplate: 'https://esm.sh/{package}@{version}',
    supportESM: true,
    supportVersions: true,
    region: 'global',
  },
  {
    id: 'skypack',
    name: 'Skypack',
    description: 'The CDN for modern web apps',
    baseUrl: 'https://cdn.skypack.dev',
    enabled: true,
    priority: 4,
    jsTemplate: 'https://cdn.skypack.dev/{package}@{version}',
    cssTemplate: 'https://cdn.skypack.dev/{package}@{version}',
    supportESM: true,
    supportVersions: true,
    region: 'global',
  },
  // npm 官方镜像
  {
    id: 'npm-registry',
    name: 'npm Registry (tarball)',
    description: 'Official npm registry tarball',
    baseUrl: 'https://registry.npmjs.org',
    enabled: false, // 默认关闭，因为需要特殊处理
    priority: 5,
    jsTemplate: 'https://registry.npmjs.org/{package}/-/{package}-{version}.tgz',
    cssTemplate: 'https://registry.npmjs.org/{package}/-/{package}-{version}.tgz',
    searchApi: 'https://api.npms.io/v2/search?q={package}',
    versionsApi: 'https://registry.npmjs.org/{package}',
    supportESM: false,
    supportVersions: true,
    region: 'global',
  },
  // 国内源
  {
    id: 'bytedance',
    name: '字节跳动 CDN',
    description: '国内高速 CDN 服务',
    baseUrl: 'https://lf3-cdn-tos.bytecdntp.com',
    enabled: true,
    priority: 6,
    jsTemplate: 'https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/{package}@{version}',
    cssTemplate: 'https://lf3-cdn-tos.bytecdntp.com/cdn/expire-1-M/{package}@{version}',
    supportESM: false,
    supportVersions: true,
    region: 'china',
  },
  {
    id: 'bootcdn',
    name: 'BootCDN',
    description: '稳定、快速、免费的前端开源项目 CDN',
    baseUrl: 'https://cdn.bootcdn.net',
    enabled: true,
    priority: 7,
    jsTemplate: 'https://cdn.bootcdn.net/ajax/libs/{package}/{version}',
    cssTemplate: 'https://cdn.bootcdn.net/ajax/libs/{package}/{version}',
    searchApi: 'https://api.bootcdn.cn/libraries/{package}.json',
    supportESM: false,
    supportVersions: true,
    region: 'china',
  },
  {
    id: 'staticfile',
    name: '七牛云 CDN',
    description: '七牛云静态文件 CDN',
    baseUrl: 'https://cdn.staticfile.org',
    enabled: true,
    priority: 8,
    jsTemplate: 'https://cdn.staticfile.org/{package}/{version}',
    cssTemplate: 'https://cdn.staticfile.org/{package}/{version}',
    supportESM: false,
    supportVersions: true,
    region: 'china',
  },
  // 自定义源示例
  {
    id: 'custom-1',
    name: 'Custom CDN 1',
    description: 'User defined custom CDN source',
    baseUrl: '',
    enabled: false,
    priority: 99,
    jsTemplate: 'https://your-cdn.com/{package}@{version}',
    cssTemplate: 'https://your-cdn.com/{package}@{version}',
    supportESM: false,
    supportVersions: false,
    region: 'global',
  },
];

export const DEFAULT_CONFIG: ConsoleImporterConfig = {
  defaultProvider: 'jsdelivr',
  providers: DEFAULT_PROVIDERS,
  autoFallback: true,
  showNotifications: true,
  cacheEnabled: true,
  cacheTime: 30 * 60 * 1000, // 30 分钟
};
